### ISSUE TITLE
Using Buffer without `new` will soon stop working after Node 7?

### ISSUE THREAD

**Issue by wuzeru** [alexeyten/qr-image#34]
(node:30742) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

Maybe u should change the use of Buffer

**Comment by renambot-uic** [comment]
I added a pull request for this. Just a few 'new'. It seems to work fine.

**Comment by Mithgol** [comment]
For future references, that pull request is #35.

**Comment by alexeyten** [comment]
#37

**Comment by niceue** [comment]
Buffer() is deprecated due to security and usability issues.
See: https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/

What you would do in this case is to convert all new Buffer() or Buffer() calls to use Buffer.alloc() or Buffer.from(), in the following way:

For new Buffer(number), replace it with Buffer.alloc(number).
For new Buffer(string) (or new Buffer(string, encoding)), replace it with Buffer.from(string) (or Buffer.from(string, encoding)).
For all other combinations of arguments (these are much rarer), also replace new Buffer(...arguments) with Buffer.from(...arguments).
Note that Buffer.alloc() is also faster on the current Node.js versions than new Buffer(size).fill(0), which is what you would otherwise need to ensure zero-filling.

**Comment by alqu** [comment]
As @niceue already stated, this error is still there and could be easily circumvented as described above.

When using ncc to "compile" the app then this error 
`[DEP0005] DeprecationWarning: Buffer() is deprecated due to ...` is spit out.

Thoughts?
